image: docker:latest
variables:
  IMAGE_TAG_VERSION: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
services:
- docker:dind
stages:
- build
build:
  stage: build
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build --cache-from $IMAGE_TAG_LATEST -t $IMAGE_TAG_LATEST .
  - docker push $IMAGE_TAG_LATEST
  only:
  - tags
  tags:
  - docker
